bundler_args: "--without production"
before_script:
  - "cp config/database.yml.example config/database.yml"
  - "cp config/setup_conf.yml.example config/setup_conf.yml"
script: rake --trace 2>&1
rvm:
  - 1.9.2
