bundler_args: "--without production"
before_script:
  - "cp config/database.yml.example config/database.yml"
  - "cp config/application.yml.example config/application.yml"
script: bundle exec rake travis
rvm:
  - 1.9.2
  - 1.9.3
