require 'spec_helper'

describe WebconfRoomsController do
  include Shoulda::Matchers::ActionController

  describe "routing" do

    # standard routes generated by bigbluebutton_rails
    it {
      should route(:get, "/webconf/rooms").
        to(:action => :index)
    }
    it {
      should route(:get, "/webconf/rooms/new").
        to(:action => :new)
    }
    it {
      should route(:get, "/webconf/rooms/external").
        to(:action => :external)
    }
    it {
      should route(:post, "/webconf/rooms/external").
        to(:action => :external_auth)
    }
    it {
      should route(:get, "/webconf/rooms/room-1/edit").
        to(:action => :edit, :id => "room-1")
    }
    it {
      should route(:get, "/webconf/rooms/room-1").
        to(:action => :show, :id => "room-1")
    }
    it {
      should route(:put, "/webconf/rooms/room-1").
        to(:action => :update, :id => "room-1")
    }
    it {
      should route(:delete, "/webconf/rooms/room-1").
        to(:action => :destroy, :id => "room-1")
    }
    it {
      should route(:get, "/webconf/rooms/room-1/join").
        to(:action => :join, :id => "room-1")
    }
    it {
      should route(:get, "/webconf/rooms/room-1/join_mobile").
        to(:action => :join_mobile, :id => "room-1")
    }
    it {
      should route(:get, "/webconf/rooms/room-1/running").
        to(:action => :running, :id => "room-1")
    }
    it {
      should route(:get, "/webconf/rooms/room-1/end").
        to(:action => :end, :id => "room-1")
    }
    it {
      should route(:get, "/webconf/rooms/room-1/invite").
        to(:action => :invite, :id => "room-1")
    }
    it {
      should route(:post, "/webconf/rooms/room-1/join").
        to(:action => :auth, :id => "room-1")
    }

  end

end
