require 'spec_helper'

describe CustomServersController do
  include Shoulda::Matchers::ActionController

  # standard routes generated by bigbluebutton_rails
  describe "routing" do
    it { should route(:get, "/bigbluebutton/servers").to(:action => :index) }
    it { should route(:post, "/bigbluebutton/servers").to(:action => :create) }
    it { should route(:get, "/bigbluebutton/servers/new").to(:action => :new) }
    it { should route(:get, "/bigbluebutton/servers/server-1/edit").to(:action => :edit, :id => "server-1") }
    it { should route(:get, "/bigbluebutton/servers/server-1").to(:action => :show, :id => "server-1") }
    it { should route(:put, "/bigbluebutton/servers/server-1").to(:action => :update, :id => "server-1") }
    it { should route(:delete, "/bigbluebutton/servers/server-1").to(:action => :destroy, :id => "server-1") }
    it { should route(:get, "/bigbluebutton/servers/server-1/activity").to(:action => :activity, :id => "server-1") }
  end

end

