require 'spec_helper'

describe WebconfServersController do
  describe "routing" do

    # standard routes generated by bigbluebutton_rails
    it { should route(:get, "/manage/webconf/servers").to(:action => :index) }
    it { should route(:post, "/manage/webconf/servers").to(:action => :create) }
    it { should route(:get, "/manage/webconf/servers/new").to(:action => :new) }
    it { should route(:get, "/manage/webconf/servers/server-1/edit").to(:action => :edit, :id => "server-1") }
    it { should route(:get, "/manage/webconf/servers/server-1").to(:action => :show, :id => "server-1") }
    it { should route(:put, "/manage/webconf/servers/server-1").to(:action => :update, :id => "server-1") }
    it { should route(:delete, "/manage/webconf/servers/server-1").to(:action => :destroy, :id => "server-1") }
    it { should route(:get, "/manage/webconf/servers/server-1/activity").to(:action => :activity, :id => "server-1") }

  end
end
